version: '3.9'

services:
  notification-service:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - '${NOTIFICATION_SERVICE_API_PORT}:8000'
    command: 'uvicorn --factory application.api.main:create_app --reload --host 0.0.0.0 --port 8000'
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
#    networks:
#      - backend
    depends_on:
      - mongodb


#networks:
#  backend:
#    driver: bridge
