version: '3.9'

services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - '${MONGODB_PORT}:27017'
    volumes:
      - notification_service_mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    networks:
      - backend

volumes:
  notification_service_mongo_data:

networks:
  backend:
    driver: bridge